[workspace]
resolver = "2"
members = [
  "api",
  "api/persistent/s3",
  "api/persistent/temp",
  "common",
  "modules/gdown",
  "modules/web",
  "pallet",
  "runtime",
]
default-members = ["runtime"]
