[package]
name = "ipdis-api-persistent-s3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipis = { git = "https://github.com/ulagbulag-village/ipis", features = [
    "derive",
] }
ipdis-common = { path = "../../../common" }

http = "0.2"
rust-s3 = "0.31"
