[package]
name = "ipdis-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(target_os = "wasi"))'.dependencies]
ipdis-api-native = { path = "./native" }

[target.'cfg(target_os = "wasi")'.dependencies]
ipdis-api-wasi = { path = "./wasi" }
