[package]
name = "ipdis-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["s3"]
s3 = ["ipdis-api-s3"]

[dependencies]
ipdis-api-s3 = { path = "s3", optional = true }

[dev-dependencies]
ipis = { git = "https://github.com/ulagbulag-village/ipis" }

bytecheck = "0.6"
rkyv = { version = "0.7", features = ["archive_be"] }
tokio = { version = "1.18", features = ["full"] }
